# Schema for the configuration files of the Systemseed Tailwind Base theme theme.
tailwind_base.settings:
  type: theme_settings
  label: 'Systemseed Tailwind Base theme settings'
  mapping:
    example:
      type: string
      label: Example
